package me.christopherwmm.terra.noise;

/**
 * The abstract superclass for all generators.
 * 
 * @param <T>
 * @since 1.0
 * @author ChristopherWMM
 */
public abstract class Generator<T> {

	/**
	 * Constructs a new T object with the specific corresponding parameters entered into this {@link Generator} object.
	 * 
	 * @return The T object generated by this {@link Generator} object.
	 */
	public abstract T generate();
}
